# Form implementation generated from reading ui file 'functiontile.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class _Ftile(QtWidgets.QWidget):
    pass
class FunctionTile(QtWidgets.QWidget):
    def __init__(self,name):
        super().__init__()
        VLayout = QtWidgets.QVBoxLayout()
        VLayout.addStretch()
        self._Ftile = _Ftile()
        VLayout.addWidget(self._Ftile)
        self.FuncName = QtWidgets.QLabel()
        VLayout.addWidget(self.FuncName)
        self.FuncName.setText("FUNCTION")
        self.Slider = QtWidgets.QSlider()
        self.Slider.setObjectName(name)
        self.Slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        
        VLayout.addWidget(self.Slider)
        self.setLayout(VLayout)


       