# Form implementation generated from reading ui file 'functiontile.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class FunctionTile(QtWidgets.QWidget):
    def __init__(self,Form):
        super().__init__()
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.FunctionTileLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.FunctionTileLayout.setContentsMargins(0, 0, 0, 0)
        self.FunctionTileLayout.setObjectName("FunctionTileLayout")
        self.FunctionNameLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.FunctionNameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.FunctionNameLabel.setObjectName("FunctionNameLabel")
        self.FunctionTileLayout.addWidget(self.FunctionNameLabel)
        self.FunctionSlider = QtWidgets.QSlider(parent=self.verticalLayoutWidget)
        self.FunctionSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.FunctionSlider.setObjectName("FunctionSlider")
        self.FunctionTileLayout.addWidget(self.FunctionSlider)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.FunctionNameLabel.setText(_translate("Form", "TextLabel"))

    def addFuntion(self,funct):
        self.FunctionSlider.valueChanged.connect(funct)
    def setText(self,text):
        self.FunctionNameLabel.setText(text)
