# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import glob
import math

from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from tkinter import filedialog

from PyQt6.QtGui import QAction


global activePath


class _Ptile(QtWidgets.QWidget):
    pass
class PhotoTile(QtWidgets.QWidget):
    def __init__(self,path):
        super().__init__()
        self.path = path
        name = (path.split('/')[-1].split("\\")[-1])
        layout = QtWidgets.QVBoxLayout()
        layout.setContentsMargins(0,0,0,0)
        layout.addStretch()
        self._Ptile = _Ptile()
        layout.addWidget(self._Ptile)
        self._label = QtWidgets.QLabel(name)
        layout.addWidget(self._label)
        self._picture = QtWidgets.QLabel()
        self._picture.setPixmap(QtGui.QPixmap(path).scaled(QtCore.QSize(100,100)))
        layout.addWidget(self._picture)
        self._chooseButton = QtWidgets.QPushButton("Set Active")
        self._chooseButton.objectName = "_chooseButton"
        self._chooseButton.clicked.connect(self._choose)
        layout.addWidget(self._chooseButton)

        self.setLayout(layout)
    def _choose(self):

        global activePath
        activePath = self.path
        self.parent().parent().findChild(QtWidgets.QLabel, "BigPhotoLabel").setPixmap(QtGui.QPixmap(activePath))
        print(activePath)




class Ui_MainWindow():
    def __init__(self,MainWindow):
        super().__init__()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.activephoto = ""
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 79, 401, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 80, 331, 411))
        self.label.setObjectName("BigPhotoLabel")
        self.Explorerbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Explorerbutton.setGeometry(QtCore.QRect(340, 50, 75, 23))
        self.Explorerbutton.setObjectName("Explorerbutton")
        self.DropButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Explorerbutton.clicked.connect(self.loadFilePath)
        self.DropButton.setGeometry(QtCore.QRect(10, 510, 75, 23))
        self.DropButton.setObjectName("DropButton")
        self.LoadButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.LoadButton.setGeometry(QtCore.QRect(330, 510, 75, 23))
        self.LoadButton.setObjectName("LoadButton")

        self.horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(440, 500, 341, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 530, 47, 13))
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(419, 10, 371, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_3.setObjectName("label_3")
        self.PathLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.PathLabel.setGeometry(QtCore.QRect(96, 50, 231, 20))
        self.PathLabel.setText("")
        self.PathLabel.setObjectName("PathLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def photoclicked(self,path):
        self.activephoto = path


    def loadFilePath(self):
        folderpath = filedialog.askdirectory()
        self.PathLabel.setText(folderpath)
        files = glob.glob(folderpath + "/*.png")
        print(files)

        for i in reversed(range(self.gridLayout.count())):
            self.gridLayout.itemAt(i).widget().setParent(None)
        gridcount = 0
        self.gridLayout.setColumnMinimumWidth(1,300)
        self.gridLayout.setColumnMinimumWidth(2, 300)
        self.gridLayout.setColumnMinimumWidth(3, 300)
        for file in files:

            self.gridLayout.addWidget(PhotoTile(file),math.floor(gridcount/3),gridcount%3)
            print(self.gridLayout.itemAt(gridcount).widget().children()[0])


            gridcount += 1
        print(self.gridLayout.count())
    def photoSelected(self,path):
        self.activephoto = path
        self.label_3.setPixmap(QtGui.QPixmap(self.activephoto).scaled(QtCore.QSize(100,100)))







    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.Explorerbutton.setText(_translate("MainWindow", "Select Dir"))

        self.DropButton.setText(_translate("MainWindow", "Drop Photos"))
        self.LoadButton.setText(_translate("MainWindow", "Load Photo"))
        self.label_2.setText(_translate("MainWindow", "Zoom"))
        self.label_3.setText(_translate("MainWindow", "Current Path:"))
app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QMainWindow()
ui = Ui_MainWindow(window)

window.show()
app.exec()