# Form implementation generated from reading ui file 'Tabs.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import photoedit
import glob
import math
import window2
from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from tkinter import filedialog

global activePath


class _Ptile(QtWidgets.QWidget):
    pass
class PhotoTile(QtWidgets.QWidget):
    def __init__(self,path):
        super().__init__()
        self.path = path
        name = (path.split('/')[-1].split("\\")[-1])
        layout = QtWidgets.QVBoxLayout()
        layout.setContentsMargins(0,0,0,0)
        layout.addStretch()
        self._Ptile = _Ptile()
        layout.addWidget(self._Ptile)
        self._label = QtWidgets.QLabel(name)
        layout.addWidget(self._label)
        self._picture = QtWidgets.QLabel()
        self._picture.setPixmap(QtGui.QPixmap(path).scaled(QtCore.QSize(100,100)))
        layout.addWidget(self._picture)
        self._chooseButton = QtWidgets.QPushButton("Set Active")
        self._chooseButton.objectName = "_chooseButton"
        self._chooseButton.clicked.connect(self._choose)
        layout.addWidget(self._chooseButton)

        self.setLayout(layout)
    def _choose(self):

        global activePath
        activePath = self.path

        self.parent().parent().parent().parent().parent().findChild(QtWidgets.QLabel, "activePhotoDisplayLabel").setPixmap(QtGui.QPixmap(activePath))
        self.parent().parent().parent().parent().parent().findChild(QtWidgets.QSlider, "horizontalSlider").setEnabled(True)
        print(activePath)


class FileSelectWidget():
    def AddMainTab(self, MainWindow):

        MainWindow.setObjectName("MainTab")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Explorerbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Explorerbutton.setGeometry(QtCore.QRect(340, 50, 75, 23))
        self.Explorerbutton.setObjectName("Explorerbutton")
        self.Explorerbutton.clicked.connect(self.loadFilePath)
        self.horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(440, 500, 341, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(20)
        self.horizontalSlider.setDisabled(True)
        self.horizontalSlider.valueChanged.connect(lambda: self.zoomChanged())
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 530, 47, 13))
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(19, 10, 601, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.presetGLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.presetGLayout.setContentsMargins(0, 0, 0, 0)
        self.presetGLayout.setObjectName("presetGLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_3.setObjectName("label_3")
        self.pathLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.pathLabel.setGeometry(QtCore.QRect(96, 50, 231, 20))
        self.pathLabel.setText("")
        self.pathLabel.setObjectName("pathLabel")
        self.presetSelectCombo = QtWidgets.QComboBox(parent=self.centralwidget)
        self.presetSelectCombo.setGeometry(QtCore.QRect(620, 10, 171, 31))
        self.presetSelectCombo.setObjectName("presetSelectCombo")
        self.photoScrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.photoScrollArea.setGeometry(QtCore.QRect(419, 79, 371, 421))
        self.photoScrollArea.setWidgetResizable(True)
        self.photoScrollArea.setObjectName("photoScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget(parent=self.photoScrollArea)
        self.scrollAreaWidgetContents_2.setMinimumSize(331,411)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrolllayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.scrolllayout.setContentsMargins(0,0,0,0)
        self.scrolllayout.addStretch()
        self.activePhotoDisplayLabel = QtWidgets.QLabel()
        self.activePhotoDisplayLabel.setGeometry(QtCore.QRect(0, 0, 331, 411))
        self.activePhotoDisplayLabel.setObjectName("activePhotoDisplayLabel")
        self.scrolllayout.addWidget(self.activePhotoDisplayLabel)
        self.activePhotoDisplayLabel.setScaledContents(True)
        self.photoScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.tileScrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.tileScrollArea.setGeometry(QtCore.QRect(10, 80, 399, 419))
        self.tileScrollArea.setWidgetResizable(True)
        self.tileScrollArea.setObjectName("tileScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 397, 417))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.tileGlayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.tileGlayout.setContentsMargins(0, 0, 0, 0)
        self.tileGlayout.setObjectName("tileGlayout")
        self.tileScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.activePhotoNameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.activePhotoNameLabel.setGeometry(QtCore.QRect(420, 50, 351, 16))
        self.activePhotoNameLabel.setText("")
        self.activePhotoNameLabel.setObjectName("activePhotoNameLabel")

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.Explorerbutton.setText(_translate("MainWindow", "DirSelect"))
            self.label_2.setText(_translate("MainWindow", "Zoom"))
            self.label_3.setText(_translate("MainWindow", "Current Path:"))
            self.activePhotoDisplayLabel.setText(_translate("MainWindow", "TextLabel"))



    def zoomChanged(self):
        x = 331
        y = 411
        self.activePhotoDisplayLabel.setGeometry(QtCore.QRect(20,10,x * math.floor(self.horizontalSlider.value()), y * math.floor(self.horizontalSlider.value())))

    def photoClicked(self,path):
        self.activephoto = path


    def loadFilePath(self):
        folderpath = filedialog.askdirectory()
        self.pathLabel.setText(folderpath)
        files = glob.glob(folderpath + "/*.png")
        print(files)

        for i in reversed(range(self.tileGlayout.count())):
            self.tileGlayout.itemAt(i).widget().setParent(None)
        gridcount = 0
        self.tileGlayout.setColumnMinimumWidth(1,300)
        self.tileGlayout.setColumnMinimumWidth(2, 300)
        self.tileGlayout.setColumnMinimumWidth(3, 300)
        for file in files:

            self.tileGlayout.addWidget(PhotoTile(file),math.floor(gridcount/3),gridcount%3)
            print(self.tileGlayout.itemAt(gridcount).widget().children()[0])


            gridcount += 1
        print(self.tileGlayout.count())
    def photoSelected(self,path):
        self.activephoto = path
        self.label_3.setPixmap(QtGui.QPixmap(self.activephoto).scaled(QtCore.QSize(100,100)))

class Ui_MainWindow():
    def __init__(self,MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(6, 0, 781, 561))
        self.tabWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        maintab = FileSelectWidget()
        maintab.AddMainTab(self.tab)
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        photoedit.Photoedit(self.tab_3)
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "File Choice"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Photo Editing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Final Product"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Last Step"))
app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QMainWindow()
ui = Ui_MainWindow(window)

window.show()
app.exec()