# Form implementation generated from reading ui file 'secondwindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class SecondWindow():
    def __init__(self, MainWindow,path):
        super().__init__()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 602)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.optionsComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.optionsComboBox.setGeometry(QtCore.QRect(700, 0, 81, 21))
        self.optionsComboBox.setObjectName("optionsComboBox")
        self.optionsComboBox.addItem("")
        self.optionsComboBox.addItem("")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 30, 641, 491))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 639, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 641, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.photoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.photoLayout.setContentsMargins(0, 0, 0, 0)
        self.photoLayout.setObjectName("photoLayout")
        self.photoDisplayLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.photoDisplayLabel.setText("")
        self.photoDisplayLabel.setObjectName("photoDisplayLabel")
        self.photoLayout.addWidget(self.photoDisplayLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(680, 29, 120, 521))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 118, 519))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-10, 0, 131, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.menueGLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.menueGLayout.setContentsMargins(0, 0, 0, 0)
        self.menueGLayout.setObjectName("menueGLayout")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.optionsComboBox.setItemText(0, _translate("MainWindow", "test1"))
        self.optionsComboBox.setItemText(1, _translate("MainWindow", "test2"))
